name: test concurrency

on:
    workflow_dispatch:
      
concurrency:
    group: test concurrency
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: sleep 30 seconds
              run: sleep 30