name: test concurrency

on:
    workflow_dispatch:
      
concurrency:
    group: test concurrency
    cancel-in-progress: false

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: sleep 20 seconds
              run: sleep 20