name: inject-pr-title

on :
    pull_request:

jobs:
    not-save-test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout 
              uses: actions/checkout@v4
            
            - name: inject pr title
              run: |
                  title=${{github.event.pull_request.title}}
                  if [[ $title =~ ^feat ]]; then
                    echo "This is a feature pull request"
                  elif [[ $title =~ ^fix ]]; then
                    echo "This is a bug fix pull request"
                  else
                    echo "This is a general pull request"
                  fi

# save using env or custome action to save the pr title in env variable and use it in the next step, but the env variable is only available in the current job, if you want to use it in another job, you need to use the output of the step and pass it to the next job using the needs keyword.
    save-test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout 
              uses: actions/checkout@v4
            
            - name: inject pr title
              env:
                TITLE=${{github.event.pull_request.title}}
              run: |
                  if [[ $TITLE =~ ^feat ]]; then
                    echo "This is a feature pull request"
                  elif [[ $TITLE =~ ^fix ]]; then
                    echo "This is a bug fix pull request"
                  else
                    echo "This is a general pull request"
                  fi
