name: use-cashe

on:
    workflow_dispatch:
      inputs:
        using-cash:
            description: "use cashe for node"
            type: boolean
            default: true
        node-version:
            description: node version
            type: choice
            options:
              - 18.x
              - 20.x
              - 21.x
            default: 20.x
jobs:
    build:
        name: build app
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: react-app/
        steps:
            - name: checkout
              uses: actions/checkout@v4
            
            - name: setup nodejs
              uses: actions/setup-node@v3
              with:
                node-version: ${{inputs.node-version}}

            - name: download cashe
              uses: actions/cashe@v3
              if: ${{inputs.using-cash}}
              id: cashe
              with:
                path: react-app/node_modules
                key: ${{runner.os}}-node-${{hashFiles("react-app/package-lock.json")}}
                restore-keys: |
                    ${{runner.os}}-node-
            
            - name: install depa
              run: npm ci

            - name: test code
              run: npm run test

            - name: build app
              run: npm run build

            - name: deplay app
              run: echo "deplaying app"