name: Example Workflow
on: 
  push:

jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Current job: ${{ github.job }}"
          cat $GITHUB_EVENT_PATH
